README.md
ios/MakerApp.xcodeproj/project.pbxproj
ios/Podfile.lock

Readme updated to include:
- IOS local build process
- Possible build issues and solution

IOS build process

---

doc/Android Local Build.md

Document how to run `maker-starter-app` on Ubuntu 20.04 x64.

doc: android local build

---

README.md

- Link : [Establish manual build process for Iphone](https://github.com/NebraLtd/maker-starter-app/issues/13https://github.com/NebraLtd/maker-starter-app/issues/13)
- Change Log 
Added documentation on:
- Building and distributing to App store with Xcode
- iOS building process
- Archiving
- Distribution
- TestFlight
- App store

iOS app store deployment doc

---

src/locales/en.ts

Issue: https://github.com/NebraLtd/maker-starter-app/issues/11
Summary: Need to update assets so that app will have our branding and sensible text.

feat: initial text

---

src/features/hotspots/setup/HotspotSetupBluetoothError.tsx
src/features/hotspots/setup/HotspotSetupPickWifiScreen.tsx
src/features/moreTab/more/MoreListItem.tsx
src/features/onboarding/LinkAccount.tsx
src/theme/theme.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/11
- Summary: Colors matching Nebra theme
**How**
To match Nebra theme. Also disabled the [notification changes](https://github.com/NebraLtd/maker-starter-app/pull/39)
because they were not working. Incorrectly thought I did not have Helium App installed even though I do. @Andrewsopoku 
**References**
**Checklist**

feat: improved colors

---

src/features/hotspots/root/HotspotsScreen.tsx

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/32
- Summary: It is not working so removing.
**How**
Removed link from home screen.
**References**
**Checklist**

feat: remove device transfer

---

package.json
src/features/hotspots/setup/HotspotSetupPickLocationScreen.tsx
yarn.lock

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/40
- Summary:
While asserting location, app crashes on Android 12. Needs to fix mapbox error and the other warnings and errors to make the assert location feature to function correctly.
**How**
1. In [.env](https://github.com/NebraLtd/maker-starter-app/blob/main/.env.sample) file, use `MAPBOX_ACCESS_TOKEN` and `MAPBOX_STYLE_URL` from same Mapbox account.
2. Bump mapbox package version to `^8.5.0`.
**Why**: ["@react-native-mapbox-gl/maps": "^8.2.0-beta2"](https://github.com/NebraLtd/maker-starter-app/blob/66f8a9ec8941caef1aa83cc316101100968c9bdc/package.json#L50) is used before. So in Android 11+, app page with mapbox view crashes since the[ mapbox package calls the deprecated Android telemetry …

Fix mapbox error and assert location

---

src/App.tsx
src/makers/nebra/index.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/12
- Summary: Point to Nebra's official onboarding server and maker ID.
**How**
Our maker entry now holds ID=1.
**References**
**Checklist**

config: point to Nebra's onboarding server

---

ios/Nebra/Info.plist
ios/Podfile.lock

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/51
- Summary: Removal of unused camera permission. 
**How**
- On xcode, navigate to info.
- Uncheck or remove camera permission
**References**
**Checklist**

camera permission removed

---

src/components/HotspotActionSheet.tsx
src/components/HotspotActionSheetItem.tsx
src/components/HotspotListItem.tsx
src/components/HotspotMenuSheet.tsx
src/store/hotspots/hotspotsSlice.ts
src/utils/secureAccount.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/55
- Summary: Display actionable items.

Create Select Action Page

---

src/features/hotspots/root/HotspotsList.tsx
src/features/hotspots/root/WelcomeOverview.tsx
src/theme/theme.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/45
- Summary: We needed to update dark theme colors to accommodate users who have darkmode theme on.
**How**
**References**
**Checklist**

Darkmode Theme Support

---

src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx
src/features/hotspots/setup/HotspotSetupSkipLocationScreen.tsx
src/features/hotspots/setup/hotspotSetupTypes.tsx
src/locales/en.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/73
- Summary:
Update assert location button text.
**How**
**References**
**Checklist**

Update assert button

---

src/components/HotspotMenuSheet.tsx
src/features/transferHotspot/TransferHotspot.tsx

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/76
- Summary:
Display user friendly error message or success message after executing the transfer hotspot.
**How Transfer Hotspot" works:**
- Maker App compose a transfer transaction for the given hotpot and the new owner address.
- Maker App delegate this transaction to Helium Hotspot App using the deep link.
- Helium App presents the details of the transfer hotspot transaction.
- User confirms the transaction.
- Helium App submits the transaction to the chain.
- Helium App return the hash value of the pending trasaction back to the Maker App using deep link.
- Maker App displays the hash value of the pending transaction to the user.
**How to notify users after device transfer:**
- For obvious errors before submitting …

Notify users after device transfer

---

ios/Podfile.lock
src/components/HotspotActionSheet.tsx
src/components/HotspotListItem.tsx
src/components/HotspotMenuSheet.tsx

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/55
- Summary: Jump to action menu by clicking anywhere within the box of a hotspot listing, not just the three dots.
**How**
**References**
**Checklist**

Clickable hotspot List

---

ios/Podfile.lock
src/features/hotspots/setup/HotspotTxnsSubmitScreen.tsx
src/locales/en.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/78
- Summary: Transaction Submission Screen needed to be updated to suit both onboarding and updating of hotspot.
**How**
**References**
**Checklist**

Update Transaction Submission Screen

---

src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx
src/utils/assertLocationUtils.tsx
src/utils/fees.ts
src/utils/secureAccount.ts
src/utils/stakingClient.ts

**Issue**
- Link:https://github.com/NebraLtd/maker-starter-app/issues/119
- Summary:Location assertion always says fee will be paid by Nebra
**How**
**References**
**Checklist**

Location assertion message change

---

src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx
src/utils/secureAccount.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/120
- Summary: App loads forever when user tries to assert non Nebra Hotspot
**How**
**References**
**Checklist**

Non Nebra Hotspot Error Fix

---

src/components/HotspotMenuSheet.tsx
src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx
src/features/hotspots/setup/HotspotTxnsProgressScreen.tsx
src/locales/en.ts
src/utils/h3Utils.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/117
- Summary: PR for updating only antenna
**How**
**References**
**Checklist**

Antenna update only

---

src/components/HotspotConfigurationPicker.tsx
src/theme/theme.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/135
- Summary: In darkmode, some text colors are not visible.
**How**
**References**
**Checklist**

Antenna Setup darkmode updated

---

README.md

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/116
- Summary:
**How**
**References**
**Checklist**

Update Readme how to skip helium wallet handshake

---

src/utils/i18n/i18nTypes.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/77
- Summary:
Remove language select option in the settings page since English is the only option available.
**How**
**References**
**Checklist**

Remove internationalization

---

src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx
src/locales/en.ts

**Issue**
- Link: https://github.com/NebraLtd/maker-starter-app/issues/153
- Summary: Based on some of the store reviews, users seem to think the app is a paid product. We should clarify what the distinction between the dashboard and app and what's paid.
**How**
**References**
**Checklist**

Change dashboard link wording

---

ios/Nebra.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
src/features/hotspots/root/HotspotScreen.tsx
src/features/hotspots/setup/HotspotSetupPickLocationScreen.tsx
src/locales/en.ts
src/utils/config.ts
src/utils/useGetLocation.ts
src/utils/usePermissionManager.ts

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Pritam/release 2.0.3
